idle_bg = "#1f1d2e"
idle_fg = "#e0def4"
info_bg = "#31748f"
info_fg = "#191724"
good_bg = "#9ccfd8"
good_fg = "#191724"
warning_bg = "#f6c177"
warning_fg = "#191724"
critical_bg = "#eb6f92"
critical_fg = "#191724"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
