idle_bg = "#292e42"
idle_fg = "#c0caf5"
info_bg = "#7aa2f7"
info_fg = "#1a1b26"
good_bg = "#9ece6a"
good_fg = "#1a1b26"
warning_bg = "#ff9e64"
warning_fg = "#1a1b26"
critical_bg = "#f7768e"
critical_fg = "#1a1b26"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
