icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

[[block]]
block = "toggle"
format = " $icon  idle_inhibit "
command_state = "~/.config/i3status-rust/idle_state_toggle.sh"
command_on = "pkill -STOP swayidle"
command_off = "pkill -CONT swayidle"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} "
format_alt = " ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) on $device "
interval = 1

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 1

[[block]]
block = "temperature"
format = " $icon $average avg, $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 1
scale = "celsius"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
interval = 1
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "battery"
interval = 1
full_format = " $icon $percentage "
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon  $timestamp.datetime(f:'%a %d/%m %I:%M%p') "
short = " $icon  $timestamp.datetime(f:'%I:%M%p')"

[[block]]
block = "uptime"
interval = 3600

[[block]]
block = "backlight"

[[block]]
block = "scratchpad"
