[plugin]
prepend_previewers = [
  { mime = "application/epub+zip", run = "epub-preview" },
  { name = "*/", run = "eza-preview" },
  { mime = "{audio,video,image}/*", run = "mediainfo"},
  { mime = "application/subrip", run = "mediainfo" },
]

prepend_fetchers = [
{ id = "git", name = "*", run = "git" },
{ id = "git", name = "*/", run = "git" }
]

prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
]

[manager]
linemode = "size_and_mtime"
