[manager]
prepend_keymap = [
  { on = [ "E" ], run = "plugin eza-preview",  desc = "Toggle tree/list dir preview" },
  { on = [ ")" ], run = "plugin eza-preview -- --inc-level", desc = "Increment tree level" },
  { on = [ "(" ], run = "plugin eza-preview -- --dec-level", desc = "Decrement tree level" },
  { on = [ "$" ], run = "plugin eza-preview -- --toggle-follow-symlinks", desc = "Toggle tree follow symlinks" },

  # for going to the local directory
  { on = [ "g", "l" ], run = "cd $HOME/.local/", desc = "Go to the user local directory" },

  # For going to the USB directory
  { on = [ "g", "m" ], run = "cd /run/media/chris", desc = "Got the mounted usb media" },

  # Just for restoring a deleted file/folder
  { on = "u", run = "plugin restore", desc = "Restore from trash"},

  # Smart enter plugin
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
]
